#!/bin/bash
for all in scripts/*;
    do source $all
done

clear

check_root

check_available_space

install_create_dir

settings_get_path

settings_get_mountstorage

settings_verification

install_base

install_profile

install_mount

if [ $settings_mountstorage = "yes" ]
then
    install_mount_internal
fi

install_scripts

install_misc

decoration_install_finished
chroot $settings_installpath/root /bin/bash -l