#!/bin/bash

    # Getting the current, and parent directory names
    CURRENTDIR=${PWD##*/}

    # Mounting the disk image to the first available loop device
	losetup -f disk.img

    # Getting the loop device mount point
    MOUNTPOINT=$(losetup -a | grep $CURRENTDIR | awk '{print $1}' | tr -d :)

    # Mounting the loop device to the root folder
	mount -t ext4 $MOUNTPOINT root

    # Mounting the rest of the folders
	mount -o bind /dev root/dev
	mount -t proc  proc root/proc
	mount -t sysfs sysfs root/sys
	mount -t tmpfs tmpfs root/tmp
	mount -t devpts devpts root/dev/pts
    mount -o bind /sdcard root/sdcard

    # DEBUG: Listing all attached loop devices
    losetup -a